---
title: Pcmanikoth.Github.Io
timezone: UTC
remote_theme: y7kim/agency-jekyll-theme
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    Image: 
